import static org.junit.Assert.*;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.HashMap;
import java.util.Scanner;

import org.junit.Test;

/**
 * Test cases
 * 
 * NOTE: Output of test will be in stackOutput.txt
 */
public class ParserGeneratorTest {

	@Test
	public void testPhase2() throws Exception {
		String specFile = "test/phase2spec.txt";
		String inputFile = "test/phase2input.txt";
		String grammarFile = "test/grammar.txt";
		
		ScannerGenerator.run(specFile, inputFile);
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		
		Scanner scan = new Scanner(new FileReader(grammarFile));
		String line = scan.nextLine();
		String first_rule = line.substring(0,line.indexOf(" ::= "));
		LL1Parser.parse(table, "output.txt", first_rule);	//NOTE: output.txt is generated by ScannerGenerator.run() call

	}

	@Test
	public void testSimple() throws Exception {
		String grammarFile = "test/testGrammar.txt";
		
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		
		Scanner scan = new Scanner(new FileReader(grammarFile));
		String line = scan.nextLine();
		String first_rule = line.substring(0,line.indexOf(" ::= "));
		LL1Parser.parse(table, "test/simpleOutput.txt", first_rule);
	}
	
	@Test
	public void testSuperSimple() throws Exception {
		String grammarFile = "test/superSimpleGrammar.txt";
		
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		
		Scanner scan = new Scanner(new FileReader(grammarFile));
		String line = scan.nextLine();
		String first_rule = line.substring(0,line.indexOf(" ::= "));
		LL1Parser.parse(table, "test/superSimpleOutput.txt", first_rule);
	}
	
	@Test
	public void ifElseGrammar() throws Exception {
		try{
			String grammarFile = "test/ifelseGrammar.txt";
			
			HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
			
			Scanner scan = new Scanner(new FileReader(grammarFile));
			String line = scan.nextLine();
			String first_rule = line.substring(0,line.indexOf(" ::= "));
			LL1Parser.parse(table, "test/ifelseOutput.txt", first_rule);
			fail();
		}
		catch(Exception e){
			System.out.println(e.getLocalizedMessage());
		}
	}
	
	
}
