import static org.junit.Assert.*;

import java.io.FileReader;
import java.util.HashMap;
import java.util.Scanner;

import org.junit.Test;


public class ParserGeneratorTest {

	@Test
	public void testPhase2() throws Exception {
		String specFile = "test/phase2spec.txt";
		String inputFile = "test/phase2input.txt";
		String grammarFile = "test/grammar.txt";
		
		ScannerGenerator.run(specFile, inputFile);
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		
		Scanner scan = new Scanner(new FileReader(grammarFile));
		String line = scan.nextLine();
		System.out.println(line);
		String first_rule = line.substring(0,line.indexOf(" ::= "));
		LL1Parser.parse(table, "output.txt", first_rule);	//NOTE: output.txt is generated by ScannerGenerator.run() call
	}

	@Test
	public void testSimple() throws Exception {
		String grammarFile = "test/testGrammar.txt";
		
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		
		Scanner scan = new Scanner(new FileReader(grammarFile));
		String line = scan.nextLine();
		System.out.println(line);
		String first_rule = line.substring(0,line.indexOf(" ::= "));
		LL1Parser.parse(table, "test/simpleOutput.txt", first_rule);	//NOTE: output.txt is generated by ScannerGenerator.run() call
	}
}
