import java.io.FileReader;
import java.util.HashMap;
import java.util.Scanner;


public class Project {
	public static void main(String[] args) throws Exception{
		
		String specFile = "test/phase2spec.txt";
		String inputFile = "test/phase2input.txt";
		String grammarFile = "test/grammar.txt";
		
		ScannerGenerator.run(specFile, inputFile);
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		
		Scanner scan = new Scanner(new FileReader(grammarFile));
		String line = scan.nextLine();
		System.out.println(line);
		String first_rule = line.substring(0,line.indexOf(" ::= "));
		LL1Parser.parse(table, "output.txt", first_rule);	//NOTE: output.txt is generated by ScannerGenerator.run() call
	}
}
