import static org.junit.Assert.fail;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.HashMap;


public class Project {
	public static void main(String[] args) throws Exception{
		
		String specFile = "test/phase2spec.txt";
		String inputFile = "test/phase2input.txt";
		String grammarFile = "test/grammar.txt";
		
		ScannerGenerator.run(specFile, inputFile);
		HashMap<String, HashMap<String, String>> table = ParserGenerator.generateParsingTable(grammarFile);
		LL1Parser.parse(table, "output.txt");	//NOTE: output.txt is generated by ScannerGenerator.run() call
	}
}
